# Generated by Django 3.0.6 on 2020-05-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='img_path',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
