# Generated by Django 3.0.6 on 2020-05-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_album_img_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('released', models.CharField(max_length=5)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
    ]
