# Generated by Django 3.0.6 on 2020-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
