# Generated by Django 3.0.6 on 2020-06-03 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_college_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='add',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='students',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Music.Song'),
        ),
    ]
